version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres_l2_t11
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: l2_t11
  app:
    build: ./app/
    depends_on:
      - db
    container_name: app_l2_t11
    ports:
      - 8080:8080